applications/familia/urls.py
from django.urls import path,include
from . import views

app_name='familia_app'

urlpatterns = [
    path('', views.inicio, name='Index'),
    path('formulario/', views.FamiliaCreateView.as_view(), name='Formulario'),
    path('lista/', views.FamiliaListView.as_view(), name='ListaFamiliares'),
    path('delete/<pk>/', views.FamiliaDeleteView.as_view(), name='Delete'),
    path('update/<pk>/', views.FamiliaUpdateView.as_view(), name='Update'),
    path('buscar/', views.buscar, name='Buscar'),
    path("busquedanombre/", views.buscar_familia, name="Buscarnombre"),
    


    path('zapas/', views.ZapasreateView.as_view(), name='Zapas'),
    path('listado-zapa/', views.mostrar_zapatillas, name='Listado-zapas'),
    #path('update-zapas/<pk>/', views.ZapasUpdateView.as_view(), name='Update-zapas'),
    path('update-zapas/<id>/', views.actualizar, name='Update-zapas'),
    path('delete-zapas/<id>/', views.eliminar_zapas, name='Delete-zapas'),
    path('buscar-zapas/', views.buscar2, name='Buscar-zapas'),
    path("busquedazapas/", views.buscar_zapa, name="Buscarzapas"),

    path('listar/',views.MascotasListView.as_view(),name='ListaMascotas'),
    path('crear/', views.MascotaCreateView.as_view(), name='CrearMascota'),
    path('delete-mascota/<pk>/', views.MascotaDeleteView.as_view(), name='Delete-mascota'),
    path('update-mascota/<pk>/', views.MascotaUpdateView.as_view(), name='Update-mascota'),
    path('search/',views.searchMascot, name='search'),

]

coder/urls.py
from email.mime import application
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('applications.familia.urls')),
]

applications/familia/models.py
from pyexpat import model
from django.db import models

# Create your models here.

class Familia(models.Model):
    Sex_choises=(
        ('0', 'Hombre'),
        ('1', 'Mujer'),
        ('2', 'otro'),
    )
    type_family_chises=(
    ('0', 'Padre'),
    ('1', 'Madre'),
    ('2', 'Hijo'),
    ('3', 'Cuñao'),
    )

    nombre = models.CharField('Nombre: ', max_length=20)
    apellido = models.CharField('Apellido', max_length=10)
    edad = models.PositiveIntegerField()
    sexo = models.CharField('Sexo', max_length=1, choices=Sex_choises)
    parentezco = models.CharField('Parentezco Familiar:', max_length=1, choices=type_family_chises)
    dni = models.CharField('DNI:', max_length=10)
    fecha_nac = models.DateField('Fecha Nacimiento: ', blank=True, null=True)

    def __str__(self):
        return f"{self.nombre} {self.apellido}"


class Zapas(models.Model):
    nombre = models.CharField('Nombre', max_length=50)
    precio = models.IntegerField()
    fecha_v = models.DateField('Fecha venta', auto_now=False, auto_now_add=False)

    
class Mascotas(models.Model):
    Sex_choises=(
        ('0', 'Macho'),
        ('1', 'Hembra'),
    )
    nombre = models.CharField('Nombre: ',max_length=20)
    raza = models.CharField('Raza: ',max_length=20)
    edad = models.PositiveIntegerField()
    fecha_nac = models.DateField('Fecha Nacimiento: ', blank=True, null=True) 
    sexo = models.CharField('Sexo', max_length=1, choices=Sex_choises)

applications/familia/forms.py
from django import forms

from .models import Familia, Zapas


from dataclasses import field, fields
from django import forms

from .models import Familia, Mascotas


class FamiliaForm(forms.ModelForm):
    """Form definition for Famila."""

    class Meta:
        """Meta definition for Familaform."""

        model = Familia
        fields = ('__all__')
        widgets={
            'fecha_nac':forms.TextInput(
                attrs={
                    'placeholder':'27/07/2013'
                }
            ),
            'nombre':forms.TextInput(
                attrs={
                    'placeholder':'Ingresa tu nombre en MAYUSCULAS'
                }
            )
        }
       
class MascotasForm(forms.ModelForm):

    class Meta:
        model =Mascotas
        fields =('__all__')
        widgets={
            'fecha_nac':forms.TextInput(
                attrs={
                    'placeholder':'27/07/2013'
                }
            )
        }


class ZapasForm(forms.ModelForm):
    """Form definition for Famila."""

    class Meta:
        """Meta definition for Familaform."""

        model = Zapas
        fields = ('__all__')
        widgets={
            'fecha_v':forms.DateInput(
                attrs={
                    'type':'date',
                }
            
            )
       
        }

applications/familia/views.py
from django.shortcuts import render, redirect
from django.views.generic import CreateView, ListView, DeleteView, UpdateView
from django.urls import reverse_lazy

from .forms import FamiliaForm, ZapasForm
from .models import Familia, Zapas

from .forms import FamiliaForm, MascotasForm
from .models import Familia, Mascotas

# Create your views here.

def inicio(request):

    return render(request, 'index.html')
    
class FamiliaCreateView(CreateView):
    template_name = "familia/add_familia.html"
    model = Familia
    form_class=FamiliaForm
    success_url=reverse_lazy('familia_app:ListaFamiliares')

def buscar_familia(request):
    return render(request, "familia/listar.html")

def buscar(request): 

    if request.GET['nombre']:
        nombre=request.GET['nombre']
        resultado=Familia.objects.filter(nombre__icontains=nombre)
        return render(request, "familia/buscar.html", {"resultado":resultado} )
    else:
        return render(request, "familia/buscar.html")
 
class FamiliaListView(ListView):
    template_name = "familia/listar.html"
    model = Familia
    context_object_name="lista"


class FamiliaDeleteView(DeleteView):
    model = Familia
    template_name = "familia/delete.html"
    success_url =  reverse_lazy('familia_app:ListaFamiliares')


class FamiliaUpdateView(UpdateView):
    model = Familia
    template_name = "familia/update.html"
    # fields=('__all__')
    form_class=FamiliaForm
    success_url =  reverse_lazy('familia_app:ListaFamiliares')

######### Mascotas #########
class MascotasListView(ListView):
    model= Mascotas
    template_name = "mascotas/listar.html"
    context_object_name="lista"



class ZapasreateView(CreateView):
    model = Zapas
    template_name = "familia/zapas.html"
    form_class=ZapasForm
    success_url=reverse_lazy('familia_app:Listado-zapas')



def mostrar_zapatillas(request):
    zapatillas=Zapas.objects.all()
    return render(request, 'familia/listado-zapatillas.html', {'zapatillas':zapatillas})

def buscar_zapa(request):
    return render(request, "familia/listado-zapatillas.html")

def buscar2(request): 

    if request.GET['nombre']:
        nombre=request.GET['nombre']
        resultado=Zapas.objects.filter(nombre__icontains=nombre)
        return render(request, "familia/buscar-zapas.html", {"resultado":resultado} )
    else:
        return render(request, "familia/buscar-zapas.html")


def actualizar(request, id):
    zapatillas=Zapas.objects.get(id=id)

    if request.method=="POST":
        formulario=ZapasForm(request.POST)
        if formulario.is_valid():
            informacion=formulario.cleaned_data
            zapatillas.nombre=informacion['nombre']
            zapatillas.precio=informacion['precio']
            zapatillas.fecha_v=informacion['fecha_v']
            
            
            zapatillas.save()
            return redirect("familia_app:Listado-zapas")

    else:
        formulario = ZapasForm(initial={"nombre":zapatillas.nombre, "precio":zapatillas.precio, "fecha_v":zapatillas.fecha_v})

    return render(request, "familia/update-zapas.html",{"form":formulario})

def eliminar_zapas(request, id):
    zapas=Zapas.objects.get(id=id)
    zapas.delete()

    return render(request, 'index.html')

class MascotaCreateView(CreateView):
    template_name = "mascotas/add_mascota.html"
    model = Mascotas
    form_class=MascotasForm
    success_url=reverse_lazy('familia_app:ListaMascotas')

class MascotaDeleteView(DeleteView):
    template_name = "mascotas/delete.html"
    model = Mascotas
    success_url=reverse_lazy('familia_app:ListaMascotas')

class MascotaUpdateView(UpdateView):
    template_name = "mascotas/update.html"
    model = Mascotas
    form_class=MascotasForm
    success_url=reverse_lazy('familia_app:ListaMascotas')

def searchMascot(request): 

    if request.GET['nombre']:
        nombre=request.GET['nombre']
        resultado=Mascotas.objects.filter(nombre__icontains=nombre)
        return render(request, "mascotas/search.html", {"resultado":resultado} )
    else:
        return render(request, "mascotas/search.html")

templates/familia/add_familia.html
{% extends 'home.html' %}
{% load static %}


{% block title %}
Agregar Familia
{% endblock title %}


{% block content %}
{% include 'includes/header.html' %}
<div class="grid-container">
    <h3>Formulario familiar</h3>
    <form method="post">{% csrf_token %}
        <div class="grid-x grid-padding-x">
            <div class="medium-6 cell">
                <label>Nombre
                    {{form.nombre}}
                </label>
            </div>
            <div class="medium-6 cell">
                <label>Apellido
                    {{form.apellido}}
                </label>
            </div>
            <div class="medium-6 cell">
                <label>edad
                    {{form.edad}}
                </label>
            </div>
            <div class="medium-6 cell">
                <label>dni
                    {{form.dni}}
                </label>
            </div>
            <div class="medium-6 cell">
                <label>sexo
                    {{form.sexo}}
                </label>
            </div>
            <div class="medium-6 cell">
                <label>parentezco
                    {{form.parentezco}}
                </label>
            </div>
            <div class="medium-6 cell">
                <label>Fecha nacimiento
                    {{form.fecha_nac}}
                </label>
            </div>
        </div>
        <div class="medium-6 cell">
            <button class="submit success button">Save</button>
        </div>
    </form>
</div>
{% include 'includes/footer.html' %}
{% endblock content %}

templates/familia/buscar-zapas.html
{% extends 'home.html' %}
{% load static %}


{% block title %}
Listado Zapatillas
{% endblock title %}


{% block content %}
{% include 'includes/header.html' %}


<table>
  <thead>
    <tr>
      <th>Nombre</th>
      <th>Precio</th>
      <th>Fecha Venta</th>

    </tr>
  </thead>
  {% for i in resultado %}
  <tbody>
    <tr>

      <td>{{i.nombre}}</td>
      <td>{{i.precio}}</td>
      <td>{{i.fecha_v}}</td>
     
      <td><a class="button success" href="{% url 'familia_app:Update-zapas' i.id %}">Actualizar</a><a class="button alert"
          href="{% url 'familia_app:Delete-zapas' i.id %}">Eliminar</a></td>

    </tr>
    
  </tbody>
  {% endfor %}
</table>
{% include 'includes/footer.html' %}
{% endblock content %}

templates/familia/buscar.html
{% extends 'home.html' %}
{% load static %}


{% block title %}

lista Familia
{% endblock title %}


{% block content %}
{% include 'includes/header.html' %}


<table>
  <thead>
    <tr>
      <th>Nombre</th>
      <th>Apellido</th>
      <th>Edad</th>
      <th>DNI</th>
      <th>fecha_nac</th>
      <th width="300">Editar</th>
    </tr>
  </thead>
  {% for i in resultado %}
  <tbody>
    <tr>

      <td>{{i.nombre}}</td>
      <td>{{i.apellido}}</td>
      <td>{{i.edad}}</td>
      <td>{{i.dni}}</td>
      <td>{{i.fecha_nac}}</td>
      <td><a class="button success" href="{% url 'familia_app:Update' i.id %}">Actualizar</a><a class="button alert"
          href="{% url 'familia_app:Delete' i.id %}">Eliminar</a></td>

    </tr>
    
  </tbody>
  {% endfor %}
</table>
{% include 'includes/footer.html' %}
{% endblock content %}

templates/familia/delete-zapas.html
{% extends 'home.html' %}
{% load static %}


{% block title %}
Agregar Familia
{% endblock title %}


{% block content %}
{% include 'includes/header.html' %}
<div class="grid-container">
    <form method="post">{% csrf_token %}
        <div class="grid-x grid-padding-x">
            <div class="medium-6 cell">
                <label><h4>Desea eliminar??</h4></label>
                <button type="submit" class="alert button">Confirmar</button>
            </div>

</div>
</form>

{% include 'includes/footer.html' %}
{% endblock content %}

templates/familia/delete.html
{% extends 'home.html' %}
{% load static %}


{% block title %}
Agregar Familia
{% endblock title %}


{% block content %}
{% include 'includes/header.html' %}
<div class="grid-container">
    <h3>Eliminar a {{object.nombre}}</h3>
    <form method="post">{% csrf_token %}
        <div class="grid-x grid-padding-x">
            <div class="medium-6 cell">
                <label><h4>Desea eliminar??</h4></label>
                <button type="submit" class="alert button">Confirmar</button>
            </div>

</div>
</form>

{% include 'includes/footer.html' %}
{% endblock content %}

templates/familia/listado-zapatillas.html
{% extends 'home.html' %}
{% load static %}


{% block title %}
Listado Zapatillas
{% endblock title %}


{% block content %}
{% include 'includes/header.html' %}

<table>
  <thead>
    <tr>
      <th>Nombre</th>
      <th>Precio</th>
      <th>Fecha Venta</th>

    </tr>
  </thead>
  {% for i in zapatillas %}
  <tbody>
    <tr>

      <td>{{i.nombre}}</td>
      <td>{{i.precio}}</td>
      <td>{{i.fecha_v}}</td>
     
      <td><a class="button success" href="{% url 'familia_app:Update-zapas' i.id %}">Actualizar</a><a class="button alert"
          href="{% url 'familia_app:Delete-zapas' i.id %}">Eliminar</a></td>

    </tr>
    
  </tbody>
  {% endfor %}
</table>

{% endblock content %}

templates/familia/listar.html
{% extends 'home.html' %}
{% load static %}


{% block title %}

lista Familia
{% endblock title %}


{% block content %}
{% include 'includes/header.html' %}
<div class="grid-container">
  <form action="/buscar/" , method="GET">
    <div class="grid-x grid-padding-x">
      <div class="medium-6 cell">
        <label>Nombre: 
          <input type="text" , name="nombre">
      </label>
       
      </div>
      <div class=" cell">
        <button class="submit success button">Save</button>
      </div>
    </div>
  </form>
</div>

<table>
  <thead>
    <tr>
      <th>Nombre</th>
      <th>Apellido</th>
      <th>Edad</th>
      <th>DNI</th>
      <th>fecha_nac</th>
      <th width="300">Editar</th>
    </tr>
  </thead>
  {% for i in lista %}
  <tbody>
    <tr>

      <td>{{i.nombre}}</td>
      <td>{{i.apellido}}</td>
      <td>{{i.edad}}</td>
      <td>{{i.dni}}</td>
      <td>{{i.fecha_nac}}</td>
      <td><a class="button success" href="{% url 'familia_app:Update' i.id %}">Actualizar</a><a class="button alert"
          href="{% url 'familia_app:Delete' i.id %}">Eliminar</a></td>

    </tr>

  </tbody>
  {% endfor %}
</table>
{% include 'includes/footer.html' %}
{% endblock content %}

templates/familia/update-zapas.html
{% extends 'home.html' %}
{% load static %}


{% block title %}
Agregar Familia
{% endblock title %}


{% block content %}
{% include 'includes/header.html' %}
<div class="grid-container">
    <h3>Formulario familiar</h3>
    <form method="post" action="">{% csrf_token %}
        <div class="grid-x grid-padding-x">
            <div class="medium-6 cell">
                <label>Nombre
                    {{form.nombre}}
                </label>
            </div>
            <div class="medium-6 cell">
                <label>Precio
                    {{form.precio}}
                </label>
            </div>
            <div class="medium-6 cell">
                <label>Fecha venta
                    {{form.fecha_v}}
                </label>
            </div>
            
        </div>
        <div class="medium-6 cell">
            <button class="submit success button">Save</button>
        </div>
    </form>
</div>

{% include 'includes/footer.html' %}
{% endblock content %}

templates/familia/update.html
{% extends 'home.html' %}
{% load static %}


{% block title %}
Actualizar Familia
{% endblock title %}


{% block content %}
{% include 'includes/header.html' %}
<div class="grid-container">
    <h3>Formulario familiar</h3>
    <form method="post">{% csrf_token %}
        <div class="grid-x grid-padding-x">
            <div class="medium-6 cell">
                <label>Nombre
                    {{form.nombre}}
                </label>
            </div>
            <div class="medium-6 cell">
                <label>Apellido
                    {{form.apellido}}
                </label>
            </div>
            <div class="medium-6 cell">
                <label>Edad
                    {{form.edad}}
                </label>
            </div>
            <div class="medium-6 cell">
                <label>DNI
                    {{form.dni}}
                </label>
            </div>
            <div class="medium-6 cell">
                <label>Sexo
                    {{form.sexo}}
                </label>
            </div>
            <div class="medium-6 cell">
                <label>Parentezco
                    {{form.parentezco}}
                </label>
            </div>
            <div class="medium-6 cell">
                <label>Fecha Nacimiento
                    {{form.fecha_nac}}
                </label>
            </div>
        </div>
        <div class="medium-6 cell">
            <button class="submit success button">Save</button>
        </div>
    </form>
</div>

{% include 'includes/footer.html' %}
{% endblock content %}

templates/familia/zapas.html
{% extends 'home.html' %}
{% load static %}


{% block title %}
Agregar Zapatillas
{% endblock title %}


{% block content %}
{% include 'includes/header.html' %}
<div class="grid-container">
    <h3>Zapatilleria Crismar</h3>
    <form method="post">{% csrf_token %}
        <div class="grid-x grid-padding-x">
            {{form}}
        <div class="medium-6 cell">
            <button class="submit success button">Save</button>
        </div>
    </form>
</div>

{% include 'includes/footer.html' %}
{% endblock content %}

templates/home.html
{% load static %}
<!DOCTYPE html>
<html lang="es">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="stylesheet" href="{% static 'css/foundation.min.css' %}">
    <title>
    {% block title %}{% endblock title %}
    </title>  
</head>
<body>
    {% block content %} {% endblock content %}
    <script src="{% static 'js/vendor/jquery.js' %}"></script>
    <script src="{% static 'js/vendor/what-input.js' %}"></script>
    <script src="{% static 'js/vendor/foundation.min.js' %}"></script>
    <script>
      $(document).foundation();
    </script>

</body>
</html>

templates/includes/footer.html
<div class="callout secondary">
  <h3 class="grid-x align-center ">Integrantes del Grupo:</h3>
    <div class="grid-x align-center">
        <div class="cell-x align-center">
          <div class="medium-6 cell">
            <h4>Camilo Astoviza
            </h4>
          </div>
          <div class="medium-6 cell">
            <h4>Gerez Roque
            </h4>
          </div>
        </div>
  </div>

templates/includes/header.html
<div class="top-bar">
    <div class="top-bar-left">
      <ul class="dropdown menu" data-dropdown-menu>
        <li class="menu-text">Pagina Familiar</li>
        <li><a href="{% url 'familia_app:Index' %}">Inicio</a></li>
        <li><a href="{% url 'familia_app:ListaFamiliares' %}">Listar Familiares</a></li>

        <li><a href="{% url 'familia_app:Listado-zapas' %}">zapatillas</a></li>

        <li><a href="{% url 'familia_app:ListaMascotas' %}">Lista Mascotas</a></li>

      </ul>
    </div>
    <div class="top-bar-right">
      <ul class="menu">
        <li><a class="button" href="{% url 'familia_app:Formulario' %}"> Registrar Familiar</a></li>
        <li><a class="button" style="background-color: green;" href="{% url 'familia_app:CrearMascota' %}"> Registrar Mascota</a></li>
        <li><a class="button" style="background-color: rgb(17, 220, 235);" href="{% url 'familia_app:Zapas' %}">Registrar zapatillas</a></li>
      </ul>
    </div>
  </div>
  

templates/index.html
{% extends 'home.html' %}
{% load static %}


{% block title %}
    Pagina inicio
{% endblock title %}
    


{% block content %}
{% include 'includes/header.html' %}
<div class="orbit" role="region" aria-label="Favorite Space Pictures" data-orbit>
    <div class="orbit-wrapper">
        <div class="orbit-controls">
            <button class="orbit-previous"><span class="show-for-sr">Previous Slide</span>&#9664;&#xFE0E;</button>
            <button class="orbit-next"><span class="show-for-sr">Next Slide</span>&#9654;&#xFE0E;</button>
        </div>
        <ul class="orbit-container">
            <li class="is-active orbit-slide">
                <figure class="orbit-figure">
                    <img class="orbit-image" src="{% static 'img/arbol.jpg' %}"  alt="Space">

                    <figcaption class="orbit-caption">Space, the final frontier.</figcaption>
                </figure>
            </li>
            <li class="orbit-slide">
                <figure class="orbit-figure">
                    <img class="orbit-image" src="{% static 'img/arbol.jpg' %}"  alt="Space">
                    <figcaption class="orbit-caption">Lets Rocket!</figcaption>
                </figure>
            </li>
           

        </ul>
    </div>
</div>
{% include 'includes/footer.html' %}
{% endblock content %}
    

templates/mascotas/add_mascota.html
{% extends 'home.html' %}
{% load static %}


{% block title %}
Agregar Mascota
{% endblock title %}


{% block content %}
{% include 'includes/header.html' %}
<div class="grid-container">
    <h3>Agregar Mascotas</h3>
    <form method="post">{% csrf_token %}
        <div class="grid-x grid-padding-x">
            <div class="medium-6 cell">
                <label>Nombre
                    {{form.nombre}}
                </label>
            </div>
            <div class="medium-6 cell">
                <label>Edad
                    {{form.edad}}
                </label>
            </div>
            <div class="medium-6 cell">
                <label>Fecha nacimiento
                    {{form.fecha_nac}}
                </label>
            </div>
            <div class="medium-6 cell">
                <label>Raza Mascota
                    {{form.raza}}
                </label>
            </div>
            <div class="medium-6 cell">
                <label>Sexo
                    {{form.sexo}}
                </label>
            </div>
        </div>
        <div class="medium-6 cell">
            <button class="submit success button">Save</button>
        </div>
    </form>
</div>
{% include 'includes/footer.html' %}
{% endblock content %}

templates/mascotas/delete.html
{% extends 'home.html' %}
{% load static %}


{% block title %}
Borrar Mascota
{% endblock title %}


{% block content %}
{% include 'includes/header.html' %}
<div class="grid-container">
    <h3>Eliminar a {{object.nombre}}</h3>
    <form method="post">{% csrf_token %}
        <div class="grid-x grid-padding-x">
            <div class="medium-6 cell">
                <label><h4>Desea eliminar??</h4></label>
                <button type="submit" class="alert button">Confirmar</button>
            </div>

</div>
</form>

{% include 'includes/footer.html' %}
{% endblock content %}

templates/mascotas/listar.html
{% extends 'home.html' %}
{% load static %}


{% block title %}
Lista Mascotas
{% endblock title %}


{% block content %}
{% include 'includes/header.html' %}

<table>
  <thead>
    <nav class="navbar navbar-light bg-light">
      <form action="/search/", method="GET">
        <p>nombre: <input type="text", name="nombre"></p>
        <input type="submit", value="Buscar">
      </form>
    </nav>
    <tr>
      <th>Nombre</th>
      <th>Edad</th>
      <th>fecha_nac</th>
      <th>Raza</th>
      <th>Sexo</th>
      <th width="300">Editar</th>
    </tr>
  </thead>
  {% for i in lista %}
  <tbody>
    <tr>

      <td>{{i.nombre}}</td>
      <td>{{i.edad}}</td>
      <td>{{i.fecha_nac}}</td>
      <td>{{i.raza}}</td>
      <td>{{i.sexo}}</td>
      <td><a class="button success" href="{% url 'familia_app:Update-mascota' i.id %}">Actualizar</a><a class="button alert"
          href="{% url 'familia_app:Delete-mascota' i.id %}">Eliminar</a></td>

    </tr>
    
  </tbody>
  {% endfor %}
</table>
{% include 'includes/footer.html' %}
{% endblock content %}

templates/mascotas/search.html
{% extends 'home.html' %}
{% load static %}


{% block title %}
Lista Mascotas
{% endblock title %}


{% block content %}
{% include 'includes/header.html' %}

<table>
  <thead>
    <tr>
      <th>Nombre</th>
      <th>Edad</th>
      <th>fecha_nac</th>
      <th>Raza</th>
      <th>Sexo</th>
      <th width="300">Editar</th>
    </tr>
  </thead>
  {% for i in resultado %}
  <tbody>
    <tr>

      <td>{{i.nombre}}</td>
      <td>{{i.edad}}</td>
      <td>{{i.fecha_nac}}</td>
      <td>{{i.raza}}</td>
      <td>{{i.sexo}}</td>
      <td><a class="button success" href="{% url 'familia_app:Update-mascota' i.id %}">Actualizar</a><a class="button alert"
          href="{% url 'familia_app:Delete-mascota' i.id %}">Eliminar</a></td>

    </tr>
    
  </tbody>
  {% endfor %}
</table>
{% include 'includes/footer.html' %}
{% endblock content %}

templates/mascotas/update.html
{% extends 'home.html' %}
{% load static %}


{% block title %}
Actualizar
{% endblock title %}


{% block content %}
{% include 'includes/header.html' %}
<div class="grid-container">
    <h3>Actualizar Mascota</h3>
    <form method="post">{% csrf_token %}
        <div class="grid-x grid-padding-x">
            <div class="medium-6 cell">
                <label>Nombre
                    {{form.nombre}}
                </label>
            </div>
            <div class="medium-6 cell">
                <label>Edad
                    {{form.edad}}
                </label>
            </div>
            <div class="medium-6 cell">
                <label>Sexo
                    {{form.sexo}}
                </label>
            </div>
            <div class="medium-6 cell">
                <label>Fecha Nacimiento
                    {{form.fecha_nac}}
                </label>
            </div>
        </div>
        <div class="medium-6 cell">
            <button class="submit success button">Save</button>
        </div>
    </form>
</div>

{% include 'includes/footer.html' %}
{% endblock content %}